"""Keyword dictionaries and regex patterns for document processing heuristics."""
from __future__ import annotations

import re

# ---------------------------------------------------------------------------
# Section headings vs. contextual hints
# ---------------------------------------------------------------------------

SECTION_HEADING_PATTERNS = {
    "scope_of_work": [
        "scope of work",
        "statement of work",
        "sow",
        "project scope",
        "work description",
        "description of work",
        "project overview",
        "background and scope",
    ],
    "mandatory_requirements": [
        "mandatory requirements",
        "mandatory criteria",
        "minimum requirements",
        "minimum mandatory",
        "must meet requirements",
        "pre-qualification requirements",
        "mandatory submission",
        "mandatory documents",
        "qualification envelope",
    ],
    "vendor_qualifications": [
        "vendor qualifications",
        "bidder qualifications",
        "proponent qualifications",
        "qualification requirements",
        "experience and qualifications",
        "eligibility requirements",
        "proponent experience",
        "minimum experience",
    ],
    "technical_requirements": [
        "technical requirements",
        "technical specifications",
        "specifications",
        "technical spec",
        "performance requirements",
        "performance specifications",
        "technical scope",
    ],
    "evaluation_criteria": [
        "evaluation criteria",
        "evaluation and scoring",
        "basis of award",
        "bid evaluation",
        "selection criteria",
        "rated criteria",
        "scoring matrix",
        "evaluation process",
        "stages of evaluation",
        "technical response evaluation",
        "commercial response evaluation",
    ],
    "location_details": [
        "location of work",
        "place of performance",
        "site location",
        "site information",
        "work site",
        "delivery location",
        "place of delivery",
        "delivery requirements",
        "on-site",
        "facility",
        "facilities",
        "service location",
        "performance location",
        "work location",
        "project location",
        "geographic",
        "nationwide",
        "multiple locations",
    ],
    "timeline_details": [
        "project schedule",
        "timeline",
        "milestones",
        "schedule of work",
        "completion schedule",
        "delivery schedule",
        "contract duration",
        "term of contract",
        "anticipated timeline",
        "contract term",
        "key dates",
    ],
}

SECTION_CONTEXT_HINTS = {
    "scope_of_work": [
        "includes but not limited to",
        "the contractor shall perform",
        "work to be performed",
        "the work includes",
        "services to be provided",
    ],
    "mandatory_requirements": [
        "shall be considered non-compliant",
        "must submit",
        "failure to provide",
        "is required to",
        "must meet all",
    ],
    "vendor_qualifications": [
        "past experience",
        "similar projects",
        "references",
        "completed at least",
        "proven track record",
        "prior work",
    ],
    "technical_requirements": [
        "shall conform to",
        "must comply with",
        "in accordance with",
        "technical standard",
        "minimum rating",
        "acceptable manufacturers",
    ],
    "evaluation_criteria": [
        "points will be awarded",
        "scored out of",
        "weighting",
        "evaluation team",
        "evaluated based on",
    ],
    "timeline_details": [
        "substantial completion",
        "final completion",
        "calendar days",
        "business days",
        "no later than",
        "within",
    ],
    "location_details": [
        "located at",
        "located in",
        "delivery to",
        "deliver to",
        "ship to",
        "shipped to",
        "address:",
        "facility address",
        "site address",
        "place of performance",
        "work will be performed",
        "services will be performed",
    ],
}

NOISE_SECTION_HEADINGS = [
    "instructions to bidders",
    "general conditions",
    "terms and conditions",
    "insurance requirements",
    "bonding requirements",
    "appendices",
    "forms",
    "tender form",
    "bid form",
]

# ---------------------------------------------------------------------------
# Sector-specific keywords
# ---------------------------------------------------------------------------

SECTOR_KEYWORDS = {
    "construction": [
        "construction",
        "roof",
        "roofing",
        "building envelope",
        "insulation",
        "mechanical room",
        "hvac",
        "plumbing",
        "electrical",
        "general contractor",
        "gc services",
        "renovation",
        "retrofit",
        "structural steel",
        "concrete",
        "asphalt",
        "paving",
        "demolition",
        "excavation",
        "foundation",
    ],
    "ammo_supply": [
        "ammunition",
        "ammo",
        "cartridge",
        "rounds",
        "munitions",
        "ball ammunition",
        "training ammunition",
        "duty ammunition",
        "calibre",
        "caliber",
        "grain",
        "fps",
        "saami",
        "cip",
        "nato spec",
        "shotgun",
        "rifle",
        "pistol",
        "handgun",
        "frangible",
        "slug",
        "buckshot",
        "target load",
    ],
    "it": [
        "it services",
        "software development",
        "software",
        "application",
        "web portal",
        "saas",
        "cloud",
        "network",
        "infrastructure",
        "database",
        "data center",
        "cybersecurity",
        "support and maintenance",
        "help desk",
        "system integration",
    ],
    "medical": [
        "medical supplies",
        "medical equipment",
        "pharmaceuticals",
        "hospital",
        "clinical",
        "healthcare",
        "diagnostic",
        "surgical",
        "laboratory",
        "patient care",
        "medical devices",
        "ppe",
        "personal protective equipment",
    ],
    "vehicle": [
        "vehicle",
        "fleet",
        "automotive",
        "truck",
        "car",
        "bus",
        "maintenance vehicle",
        "emergency vehicle",
        "police vehicle",
        "fire truck",
        "ambulance",
        "utility vehicle",
        "utv",
        "utility terrain vehicle",
        "side-by-side",
        "atv",
        "all-terrain vehicle",
        "4x4",
        "off-road vehicle",
        "recreational vehicle",
    ],
    "uniforms": [
        "uniform",
        "uniforms",
        "apparel",
        "clothing",
        "garment",
        "tactical gear",
        "duty uniform",
        "dress uniform",
        "service uniform",
        "work uniform",
        "law enforcement uniform",
        "police uniform",
        "security uniform",
        "military uniform",
        "badge",
        "insignia",
        "name tag",
        "patch",
        "embroidery",
        "quartermaster",
        "textile",
        "fabric",
        "outerwear",
        "footwear",
        "boots",
        "jacket",
        "pants",
        "trousers",
        "shirt",
        "polo",
        "tee",
        "cap",
        "hat",
        "belt",
        "vest",
        "rainwear",
        "cold weather gear",
    ],
    "food_services": [
        "food services",
        "catering",
        "meal preparation",
        "cafeteria",
        "food supply",
        "dietary",
        "kitchen equipment",
        "food safety",
    ],
    "security": [
        "security services",
        "security guard",
        "access control",
        "surveillance",
        "patrol",
        "monitoring",
        "alarm system",
        "cctv",
    ],
    "janitorial": [
        "janitorial",
        "cleaning services",
        "custodial",
        "sanitation",
        "housekeeping",
        "facility maintenance",
        "floor care",
    ],
    "professional_services": [
        "consulting",
        "advisory",
        "professional services",
        "management consulting",
        "project management",
        "training services",
        "audit",
        "legal services",
    ],
    "facilities_management": [
        "facilities management",
        "building maintenance",
        "property management",
        "landscaping",
        "grounds maintenance",
        "snow removal",
        "waste management",
    ],
    "office_supplies": [
        "office supplies",
        "stationery",
        "office furniture",
        "printing services",
        "copier",
        "toner",
        "paper products",
    ],
    "telecommunications": [
        "telecommunications",
        "telephone",
        "voip",
        "wireless",
        "cellular",
        "radio communication",
        "internet services",
        "fiber optic",
    ],
    "energy": [
        "energy",
        "electricity",
        "natural gas",
        "renewable energy",
        "solar",
        "wind power",
        "power generation",
        "utility services",
    ],
    "environmental": [
        "environmental",
        "hazmat",
        "waste disposal",
        "recycling",
        "remediation",
        "environmental assessment",
        "contamination",
        "soil testing",
    ],
    "transportation": [
        "transportation",
        "logistics",
        "freight",
        "shipping",
        "delivery",
        "courier",
        "warehousing",
        "supply chain",
    ],
}

TECHNICAL_KEYWORDS = {
    "construction": [
        "tpo membrane",
        "epdm",
        "bitumen",
        "torch-on",
        "r-value",
        "vapour barrier",
        "vapor barrier",
        "flashing",
        "parapet",
        "insulation board",
        "rigid insulation",
        "polyisocyanurate",
        "roof deck",
        "roof drains",
        "fall protection",
        "structural drawings",
        "load bearing",
        "seismic",
        "fire rating",
        "building code",
        "rebar",
        "formwork",
        "curing",
        "compressive strength",
        "aggregate",
    ],
    "ammo_supply": [
        "full metal jacket",
        "fmj",
        "hollow point",
        "hp",
        "jacketed",
        "jacketed soft point",
        "soft point",
        "lead-free",
        "reduced lead",
        "non-corrosive primer",
        "brass case",
        "steel case",
        "reloadable",
        "velocity",
        "muzzle velocity",
        "chamber pressure",
        "saami standard",
        "cip standard",
        "frangible",
        "armor piercing",
        "armour piercing",
        "barrier blind",
        "boat tail",
        "match grade",
        "duty ammunition",
        "training ammunition",
        "controlled expansion",
        "cannelure",
        "reduced recoil",
    ],
    "it": [
        "api integration",
        "rest api",
        "soap",
        "microservices",
        "high availability",
        "redundancy",
        "sla",
        "uptime",
        "latency",
        "load balancing",
        "virtual machine",
        "hypervisor",
        "container",
        "kubernetes",
        "docker",
        "ci/cd",
        "devops",
        "agile",
        "scrum",
        "git",
        "version control",
        "aws",
        "azure",
        "gcp",
    ],
    "medical": [
        "fda approved",
        "ce marked",
        "sterile",
        "single-use",
        "reusable",
        "autoclavable",
        "biocompatible",
        "latex-free",
        "disposable",
        "iso 13485",
        "gmp",
        "cleanroom",
        "pharmaceutical grade",
        "prescription",
        "over-the-counter",
        "otc",
        "dosage",
        "active ingredient",
        "expiry date",
        "batch number",
    ],
    "vehicle": [
        "chassis",
        "powertrain",
        "drivetrain",
        "fuel efficiency",
        "emissions",
        "mpg",
        "horsepower",
        "torque",
        "payload capacity",
        "towing capacity",
        "wheelbase",
        "ground clearance",
        "all-wheel drive",
        "four-wheel drive",
        "transmission",
        "suspension",
        "brake system",
        "abs",
        "airbags",
        "safety rating",
        "gvwr",
        "bed capacity",
        "cargo box",
        "winch",
        "roll cage",
        "trail rated",
        "off-road capability",
        "differential lock",
        "skid plate",
    ],
    "food_services": [
        "haccp",
        "food safety",
        "allergen-free",
        "gluten-free",
        "vegetarian",
        "vegan",
        "halal",
        "kosher",
        "nutritional value",
        "calorie count",
        "portion size",
        "serving temperature",
        "shelf life",
        "refrigeration",
        "cold chain",
    ],
    "security": [
        "security clearance",
        "background check",
        "armed guard",
        "unarmed guard",
        "patrol route",
        "incident reporting",
        "emergency response",
        "access badge",
        "biometric",
        "key card",
        "24/7 monitoring",
        "video recording",
        "motion detector",
        "alarm response",
    ],
    "janitorial": [
        "green cleaning",
        "eco-friendly",
        "disinfectant",
        "sanitizer",
        "floor wax",
        "carpet cleaning",
        "pressure washing",
        "window cleaning",
        "waste removal",
        "recycling",
        "restroom supplies",
        "paper towels",
        "hand soap",
    ],
    "professional_services": [
        "deliverable",
        "milestone",
        "statement of work",
        "work breakdown structure",
        "gantt chart",
        "risk assessment",
        "stakeholder analysis",
        "change management",
        "quality assurance",
        "best practices",
        "industry standard",
        "benchmarking",
    ],
    "facilities_management": [
        "preventive maintenance",
        "corrective maintenance",
        "work order",
        "building automation",
        "bms",
        "energy management",
        "hvac maintenance",
        "electrical maintenance",
        "plumbing repair",
        "emergency repairs",
        "scheduled maintenance",
    ],
    "office_supplies": [
        "recycled paper",
        "inkjet",
        "laser printer",
        "multifunction",
        "copier speed",
        "paper capacity",
        "duplex printing",
        "color printing",
        "ergonomic",
        "adjustable height",
        "mesh back",
        "lumbar support",
    ],
    "telecommunications": [
        "bandwidth",
        "broadband",
        "fiber to the premises",
        "fttp",
        "dsl",
        "cable modem",
        "upload speed",
        "download speed",
        "pbx system",
        "sip trunk",
        "call routing",
        "voicemail",
        "conference bridge",
        "toll-free",
    ],
    "energy": [
        "kilowatt",
        "megawatt",
        "voltage",
        "amperage",
        "transformer",
        "substation",
        "power factor",
        "load management",
        "peak demand",
        "renewable energy credit",
        "rec",
        "carbon offset",
        "net metering",
        "battery storage",
    ],
    "environmental": [
        "phase i esa",
        "phase ii esa",
        "soil sample",
        "groundwater",
        "contaminant",
        "heavy metals",
        "asbestos",
        "lead paint",
        "mold remediation",
        "air quality",
        "emission testing",
        "environmental impact",
        "epa",
        "compliance",
    ],
    "transportation": [
        "ltl",
        "ftl",
        "intermodal",
        "cross-docking",
        "distribution center",
        "last mile",
        "route optimization",
        "gps tracking",
        "proof of delivery",
        "pod",
        "bill of lading",
        "freight forwarder",
        "customs clearance",
    ],
}

# ---------------------------------------------------------------------------
# Licenses, certifications, special statuses
# ---------------------------------------------------------------------------

LICENSE_PATTERNS = [
    "licensed",
    "license",
    "licence",
    "licensed in",
    "hold a valid",
    "must hold",
    "must be licensed",
    "shall be licensed",
    "trade license",
    "contractor license",
    "electrical contractor licence",
    "plumbing licence",
]

CERTIFICATION_PATTERNS = [
    "iso",
    "iso 9001",
    "iso 14001",
    "saami",
    "cip",
    "csa",
    "astm",
    "cor certification",
    "certificate of recognition",
    "ulc",
    "ul listed",
    "nema",
]

SPECIAL_STATUS_PATTERNS = [
    "indigenous supplier",
    "indigenous-owned",
    "aboriginal business",
    "first nations",
    "women-owned",
    "woman-owned",
    "women owned",
    "minority-owned",
    "small business",
    "service-disabled veteran-owned",
    "sdvosb",
    "hubzone",
]

IDENTIFIER_REGEXES = {
    "solicitation": [
        re.compile(r"(?:solicitation|rfb|rfp|rfq|tender|bid)\s*(?:no\.?|number|#)?\s*[:=]?\s*([A-Za-z0-9\-_/]+)", re.IGNORECASE),
        re.compile(r"opp\s*-\s*\d{3,}", re.IGNORECASE),
    ],
    "reference": [
        re.compile(r"reference\s*(?:no\.?|number|#)?\s*[:=]?\s*([A-Za-z0-9\-_/]+)", re.IGNORECASE),
        re.compile(r"tender\s*(?:no\.?|number|#)?\s*[:=]?\s*(\d+)", re.IGNORECASE),
        re.compile(r"pw-\d{2}-\d{8}", re.IGNORECASE),
    ],
}

# ---------------------------------------------------------------------------
# Regex patterns
# ---------------------------------------------------------------------------

NAICS_REGEXES = [
    re.compile(r"NAICS[:\s]+(\d{6})", re.IGNORECASE),
    re.compile(r"NAICS\s+[Cc]ode[:\s]+(\d{6})", re.IGNORECASE),
    re.compile(r"(?:Primary|Main)\s+NAICS[:\s]+(\d{6})", re.IGNORECASE),
    re.compile(r"COMPETITIVE\s+NAICS[:\s]+(\d{6})", re.IGNORECASE),
    re.compile(r"8\(A\)\s+COMPETITIVE\s+NAICS[:\s]+(\d{6})", re.IGNORECASE),
]

EXPERIENCE_REGEXES = [
    re.compile(r"(\d+)\s+(years|year)\s+of\s+experience", re.IGNORECASE),
    re.compile(r"minimum\s+of\s+(\d+)\s+(years|year)\s+experience", re.IGNORECASE),
    re.compile(r"at\s+least\s+(\d+)\s+(years|year)\s+experience", re.IGNORECASE),
    re.compile(r"completed\s+at\s+least\s+(\d+)\s+projects", re.IGNORECASE),
]

VOLUME_REGEXES = [
    re.compile(r"(\d[\d,\.]+)\s*(square\s*meters?|sq\.?\s*m|m2)", re.IGNORECASE),
    re.compile(r"(\d[\d,\.]+)\s*(square\s*feet|sq\.?\s*ft|ft2)", re.IGNORECASE),
    re.compile(r"(\d[\d,\.]+)\s*(rounds|cartridges|pcs|pieces)", re.IGNORECASE),
    re.compile(r"(\d[\d,\.]+)\s*(kg|kilograms?|lbs|pounds?)", re.IGNORECASE),
    re.compile(r"(\d+)\s+(?:utility\s+)?(vehicles?|utvs?|units?)", re.IGNORECASE),
]

TIMELINE_REGEXES = [
    re.compile(r"within\s+(\d+)\s+(calendar|business)\s+days", re.IGNORECASE),
    re.compile(r"(\d+)\s+(calendar|business)\s+days\s+from\s+(award|notice)", re.IGNORECASE),
    re.compile(r"no\s+later\s+than\s+([A-Za-z]+\s+\d{1,2},\s+\d{4})", re.IGNORECASE),
    re.compile(r"substantial\s+completion\s+by\s+([A-Za-z]+\s+\d{1,2},\s+\d{4})", re.IGNORECASE),
]
