"""Add Canada contracts support - GSIN, UNSPSC, contract history

Revision ID: d8dfe206ccc1
Revises: 6b4ee64b05c3
Create Date: 2025-11-23 01:13:43.525882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8dfe206ccc1'
down_revision: Union[str, Sequence[str], None] = '6b4ee64b05c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendors', sa.Column('employee_count_range', sa.String(length=50), nullable=True))
    op.add_column('vendors', sa.Column('total_contract_value', sa.Float(), nullable=True))
    op.add_column('vendors', sa.Column('contract_count', sa.Integer(), nullable=True))
    op.add_column('vendors', sa.Column('first_contract_date', sa.Date(), nullable=True))
    op.add_column('vendors', sa.Column('last_contract_date', sa.Date(), nullable=True))
    op.add_column('vendors', sa.Column('contract_history_json', sa.JSON(), nullable=True))
    
    op.create_table(
        'vendor_gsin',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('vendor_id', sa.Integer(), nullable=False),
        sa.Column('gsin_code', sa.String(length=10), nullable=False),
        sa.Column('gsin_description', sa.String(length=500), nullable=True),
        sa.Column('is_primary', sa.Boolean(), nullable=False, server_default='false'),
        sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text('CURRENT_TIMESTAMP')),
        sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id']),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('vendor_id', 'gsin_code', name='uq_vendor_gsin')
    )
    op.create_index('ix_vendor_gsin_lookup', 'vendor_gsin', ['gsin_code', 'vendor_id'])
    op.create_index(op.f('ix_vendor_gsin_vendor_id'), 'vendor_gsin', ['vendor_id'])
    op.create_index(op.f('ix_vendor_gsin_gsin_code'), 'vendor_gsin', ['gsin_code'])
    
    op.create_table(
        'vendor_unspsc',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('vendor_id', sa.Integer(), nullable=False),
        sa.Column('unspsc_code', sa.String(length=10), nullable=False),
        sa.Column('unspsc_description', sa.String(length=500), nullable=True),
        sa.Column('is_primary', sa.Boolean(), nullable=False, server_default='false'),
        sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text('CURRENT_TIMESTAMP')),
        sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id']),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('vendor_id', 'unspsc_code', name='uq_vendor_unspsc')
    )
    op.create_index('ix_vendor_unspsc_lookup', 'vendor_unspsc', ['unspsc_code', 'vendor_id'])
    op.create_index(op.f('ix_vendor_unspsc_vendor_id'), 'vendor_unspsc', ['vendor_id'])
    op.create_index(op.f('ix_vendor_unspsc_unspsc_code'), 'vendor_unspsc', ['unspsc_code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vendor_unspsc_unspsc_code'), 'vendor_unspsc')
    op.drop_index(op.f('ix_vendor_unspsc_vendor_id'), 'vendor_unspsc')
    op.drop_index('ix_vendor_unspsc_lookup', 'vendor_unspsc')
    op.drop_table('vendor_unspsc')
    
    op.drop_index(op.f('ix_vendor_gsin_gsin_code'), 'vendor_gsin')
    op.drop_index(op.f('ix_vendor_gsin_vendor_id'), 'vendor_gsin')
    op.drop_index('ix_vendor_gsin_lookup', 'vendor_gsin')
    op.drop_table('vendor_gsin')
    
    op.drop_column('vendors', 'contract_history_json')
    op.drop_column('vendors', 'last_contract_date')
    op.drop_column('vendors', 'first_contract_date')
    op.drop_column('vendors', 'contract_count')
    op.drop_column('vendors', 'total_contract_value')
    op.drop_column('vendors', 'employee_count_range')
    # ### end Alembic commands ###
