[server]
maxUploadSize = 500
maxMessageSize = 500
enableCORS = false
enableXsrfProtection = true
maxMessageSize = 200

[browser]
gatherUsageStats = false

[runner]
magicEnabled = true
fastReruns = true
sessionIdleTimeout = 7200000

[client]
showErrorDetails = true
toolbarMode = "minimal"
