[server]
maxUploadSize = 500
maxMessageSize = 500
enableXsrfProtection = true
disconnectedSessionTTL = 3600
websocketPingInterval = 120

[browser]
gatherUsageStats = false

[runner]
magicEnabled = true
fastReruns = true

[client]
showErrorDetails = true
toolbarMode = "minimal"
